[package]
name = "zville"
version = "0.1.0"
license = "MIT"
authors = ["Nick Bryan <nickbryan.dev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
bevy = "0.2.1"
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking" }
byteorder = "1"
